### ISSUE TITLE
PRに対してPreview Deployを作成する

### ISSUE THREAD

**Issue by eggplants** [Make-IT-TSUKUBA/alternative-tsukuba-kdb#105]
[Vercel](https://vercel.com/docs/concepts/git/vercel-for-github#)や[Netlify](https://docs.netlify.com/site-deploys/deploy-previews/)を用いて、PRの変更ごとにPreview Deployが作成されるようにするとレビュー/デバッグしやすくなると思います。

**Comment by inaniwaudon** [comment]
Netlifyの方で試してみましたが、上手いこといきません……

**Comment by inaniwaudon** [comment]
デプロイプレビュー、いつの間にかちゃんと出るようになっていたんですね…… 気付かなかったです
e.g. https://deploy-preview-126--jovial-melomakarona-6a9e79.netlify.app/

**Comment by eggplants** [comment]
見てませんでした…
やっぱnetrifyくんの問題だったんでしょうか
