### ISSUE TITLE
シラバスデータ更新PRを自動化する

### ISSUE THREAD

**Issue by eggplants** [Make-IT-TSUKUBA/alternative-tsukuba-kdb#167]
現在更新PRが溜まっていますが、レビューが必要な方式だとレビュワーの不在により更新性が損なわれる問題があります。

自動マージはActions導入時権限の関係で諦めたような気がするんですが、自動化したほうが良さそうです。

TODO:

- [ ] `src/kdb.json` `tools/csv/kdb-*.csv` に対するテストを書く
- [ ] ラベル `automated pr` がついているPRがテスト通過しているならreviewなしでauto-mergeされるようにする

**Comment by onokatio** [comment]
PRじゃなくてpushではダメなんでしたっけ？

**Comment by eggplants** [comment]
「scheduled workflowとして、テスト通ればmasterにpush、落ちればissueを立てる」とかでもよさそうですね。

**Comment by onokatio** [comment]
FYI: https://blog.smartbank.co.jp/entry/2023/02/16/dependabot-auto-merge-with-github-app

**Comment by inaniwaudon** [comment]
こちらですが、auto-merge を有効にして PR を作成 → Actions によって PR が立てられた場合は自動で approve を付与することで、テストが通った場合にのみシラバスデータ更新の PR を自動マージするようにしました。これで動いていそうなので、issue は一旦 close したいと思います。
