### ISSUE TITLE
曜日・時限の選択に「集中」「応談」「随時」のみを選択する方法

### ISSUE THREAD

**Issue by ArinoriYoshiro** [Make-IT-TSUKUBA/alternative-tsukuba-kdb#189]
初めましての方ははじめまして、1利用者ですがご相談がございます。
曜日・時限で授業をソートする時、「集中」「応談」「随時」のみを選択すると「選択なし」として反映されません。
日６を選択することで実質「集中」「応談」「随時」のみ反映できるようになりますが、他に方法はありますか。

**Comment by inaniwaudon** [comment]
確認が遅くなってしまい大変申し訳ありません。
PR を作成してマージしましたので、https://make-it-tsukuba.github.io/alternative-tsukuba-kdb/ にアクセスして頂き、期待通りの挙動に修正されているかを確認していただいてもよろしいでしょうか？
