### ISSUE TITLE
GitHub Actionsによるコミットがうまくいっていない

### ISSUE THREAD

**Issue by Mimori256** [Make-IT-TSUKUBA/alternative-tsukuba-kdb#25]
ブランチが保護されていて、GitHub Actionsによる自動アップデートのコミットがうまくいっていないように見えます。

**Comment by inaniwaudon** [comment]
[https://github.community/t/allowing-github-actions-bot-to-push-to-protected-branch/16536] にあるように、REST APIで対応しないと駄目っぽいですね……

**Comment by eggplants** [comment]
失敗してました…

https://github.com/Make-IT-TSUKUBA/alternative-tsukuba-kdb/runs/2866959606?check_suite_focus=true
