### ISSUE TITLE
科目が重複して表示される

### ISSUE THREAD

**Issue by s7tya** [Make-IT-TSUKUBA/alternative-tsukuba-kdb#324]
![CleanShot 2024-04-06 at 09 23 30@2x](https://github.com/Make-IT-TSUKUBA/alternative-tsukuba-kdb/assets/53410646/b326f2ea-0563-4759-bdb8-f455f992106d)

現在、(おそらく) すべての科目が重複して表示されているようです。
これは大学院科目の `kdb-grad.json` にも学部の科目が含まれ、その両方を以下で import していることが原因のような気がします

https://github.com/Make-IT-TSUKUBA/alternative-tsukuba-kdb/blob/7138779fabe4edf90d4044664235c72c09835d65/src/subject/index.ts#L130-L131

**Comment by inaniwaudon** [comment]
報告ありがとうございます！ ご指摘の通りだったので修正しました。
