### ISSUE TITLE
履修仮組み機能に関する問題

### ISSUE THREAD

**Issue by itsu-dev** [Make-IT-TSUKUBA/alternative-tsukuba-kdb#33]
履修仮組み機能にいくつか問題を見つけたので報告します。
- お気に入りボタンを用いて登録できることを明示したほうがいい
- 「すべて削除」を押したときにお気に入りがすべて削除されることがわかるようにしたほうがいい
→ヘルプを実装するべき...？
- 「すべて削除」を押したときに★マークの表示が更新されない  
- マージ時にレビューにて報告されていた問題（私も確認しました）
> by Mimori256
> 少しテストしてみて、仮組のスケジュール上に正しく登録されないものをまとめました:
>
> EB15483 電子顕微鏡実験 秋B　木・金4-6
HC21102　機能形態学演習 春C 秋A木1,2 火4,5
9431114 国語科教育演習I 秋AB 秋C 水1 水1,2
EB90021 人間生物学II 秋B月4-6 火4,5
EB15114 理論生物学の基礎I 春AB 秋AB 金3 火3
etc.
> 
> 特に複数のモジュールごとに異なる時限が割り当てられているものが、うまくいっていないように見えます。(単位計算は正確でした。)
  
ただ、すごく便利な機能だと思います👍

**Comment by inaniwaudon** [comment]
ご指摘ありがとうございます！ #34 で対応しました。

**Comment by itsu-dev** [comment]
あありがろうございます！
