### ISSUE TITLE
Wrong courses displayed when searching for a specific module.

### ISSUE THREAD

**Issue by HiroKoni** [Make-IT-TSUKUBA/alternative-tsukuba-kdb#96]
### Description
When searching for a specific module, some courses which are not applicable to the condition are displayed as the result.

### Steps to reproduce
Search for 秋C module with course number 2853113 for example. While there is expected to be no matching courses as 2853113 is a 春C秋A集中 class, the course is displayed as the result.
This phenomenon can be observed with many 春C&秋xx courses including AB98E51 and AB98F52. The opposite occurs in 秋C&春xx courses like 3920912 and 4006032.

#### Screenshot
![image](https://user-images.githubusercontent.com/39662862/156579602-156dd623-2b30-4a12-a9b5-a7311eb971e5.png)

**Comment by eggplants** [comment]
>説明
>特定のモジュールを検索すると、条件に該当しないコースが結果に表示される。

>再現手順
>例えば、コース番号`2853113`で`秋C`モジュールを検索します。`2853113`は`春C``秋A``集中`クラスなので、一致する科目はないはずですが、結果として表示されています。
>この現象は、`AB98E51` や `AB98F52` など、多くの`春C`&`秋xx` 科目で確認できます。`3920912`や`4006032`のような`秋C`&`春xx`の科目では、その逆の現象が発生します。

**Comment by inaniwaudon** [comment]
放置していてすみません、PRを投げたので、どなたかレビューお願いできますか？

**Comment by eggplants** [comment]
ts周りに詳しそうな @frodo821 さんにreview requestを投げました。

**Comment by inaniwaudon** [comment]
解決してそうなのでclose
